Fixing bosco script to use ssh-agent for authentication.

diff --git a/src/condor_scripts/bosco_add_host b/src/condor_scripts/bosco_add_host
--- a/src/condor_scripts/bosco_add_host
+++ b/src/condor_scripts/bosco_add_host
@@ -23,39 +23,125 @@ remote_host=$1
 bosco_key=$HOME/.ssh/bosco_key.rsa
 
 # Bosco password location
-bosco_pass=$HOME/.bosco/.pass
+PASSPHRASE_LOCATION=$HOME/.bosco/.pass
 
 
 # If the key doesn't exist, create it
 if [ ! -e $bosco_key ]; then
     # Read in password for bosco key
     stty -echo
-    read -p "Enter password for bosco ssh key: " passw; echo
+    read -p "Enter password for bosco ssh key: " PASSPHRASE; echo
     stty echo
 
     # Output the password to a specially crafted file
     mkdir -p $HOME/.bosco
-    echo $passw > $bosco_pass
-    chmod go-rwx $bosco_pass
+    echo $PASSPHRASE > $PASSPHRASE_LOCATION
+    chmod go-rwx $PASSPHRASE_LOCATION
     
-    ssh-keygen -q -t rsa -f $bosco_key -P $passw
+    ssh-keygen -q -t rsa -f $bosco_key -P $PASSPHRASE
 fi
 
 
 # Transfer the public key to the remote host
 # ssh-copy-id is available on el5 from openssh-clients
+echo "Enter password to copy ssh keys to $remote_host:"
 ssh-copy-id -i $bosco_key $remote_host
 
 
 # Copy blahp
+PASSPHRASE=""
+if [ -f $PASSPHRASE_LOCATION ]; then
+    PASSPHRASE=`cat $PASSPHRASE_LOCATION`
+fi
+
+# Start the ssh-agent
+eval `ssh-agent -s`
+
+# Create an ssh-agent session to handle the transfers
+# Copied from remote_gahp
+# create a temp file for the expect script
+SSH_ADD_SCRIPT=`mktemp`
+chmod 700 $SSH_ADD_SCRIPT
+
+# Create the expect script
+echo "#!/usr/bin/expect -f
+    # get arguments
+    set num_args [llength \$argv]
+    set private_key_loc [lindex \$argv 0]
+
+    # spawn ssh-add process
+    spawn ssh-add $bosco_key
+
+    set spawn_pid [exp_pid]
+
+    # set timeout for expected input
+    set timeout 5
+
+    expect {
+        # no passphrase required
+        \"*Identity added*\" {
+            exit 0
+        }
+        # sends passphrase
+        \"*passphrase*\" {
+            send -- \"$PASSPHRASE\r\"
+        }
+        # no ssh-agent running
+        \"*authentication agent*\" {
+            exit -1
+        }
+        # incorrect private key location
+        timeout {
+            exit -2
+        }
+    }
+
+    expect {
+        # all done
+        eof {
+            exit 0
+        }
+        # incorrect passphrase
+        \"*passphrase*\" {
+            exit -3
+        }
+        # timeout
+        timeout {
+            exit -4
+        }
+    }" > $SSH_ADD_SCRIPT
+
+
+# call the expect script to ssh-add identity
+$SSH_ADD_SCRIPT
+ADD_STATUS=$?
+
+# remove temporary script
+rm $SSH_ADD_SCRIPT
+
+# check if ssh-add failed
+if [ $ADD_STATUS != 0 ] ; then
+    # ssh-add script not found
+    if [ $ADD_STATUS == 1 ] ; then
+        ADD_STATUS=-1
+    fi
+    eval `ssh-agent -sk`
+    exit $ADD_STATUS
+fi
+
 
 # First, find the blahp
 glite_location=`condor_config_val GLITE_LOCATION`
 release_dir=`condor_config_val RELEASE_DIR`
 
-# Copy over blahp
-rsync -av -e "ssh -i $bosco_key" $glite_location $remote_host:bosco/libexec/
-rsync -av -e "ssh -i $bosco_key" $release_dir/lib/libclassad.so* $remote_host:bosco/lib/
-rsync -av -e "ssh -i $bosco_key" $release_dir/lib/condor $remote_host:bosco/lib/
+# Make the necessary remote directories
+ssh $remote_host "mkdir -p bosco"
 
+# Copy over blahp
+rsync -aqv  $glite_location $remote_host:bosco/libexec/
+rsync -aqv  $release_dir/lib/libclassad.so* $remote_host:bosco/lib/
+rsync -aqv  $release_dir/lib/condor $remote_host:bosco/lib/
+
+# Shut down ssh-agent
+eval `ssh-agent -sk`
 
